name: Pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  release:
    types:
      - published

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: download default world data
        env:
          DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
      - name: download world outline data
        env:
          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
      - name: setup toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      - name: download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: build
        run: ./trunk build --release --public-url $PUBLIC_URL
        env:
          PUBLIC_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
